apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ycsb-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ycsb
  template:
    metadata:
      labels:
        app: ycsb
    spec:
      containers:
        - name: ycsb
          image: docker.io/traceherrell/ycsb:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              host_index=$(echo $HOSTNAME | grep -o '[0-9]\+')
              cd ycsb-foundationdb-binding-0.18.0-SNAPSHOT
              now=$(date +"%Y_%m_%d_%H_%M_%S")
              log_file="ycsb_host_${host_index}__$now.log"
              db_name='fdb' 
              workload='workloads/workloada'
              num_keys=10000 
              value_size_bytes=2000 
              threads_per_process=50 
              process_per_host=8 
              batch_size=100
              num_clients=1
              field_count=10
              field_length=100
              max_execution_time_seconds=300
              keys_per_host=$((num_keys / num_clients))
              keys_per_process=$((keys_per_host / process_per_host))
              start_key_offset=0
              start_key_per_host=$((host_index*keys_per_host+start_key_offset))
              while true; do
                echo "Waiting for cluster file to be created"
                if [ -f $FDB_CLUSTER_FILE ]; then
                  break
                fi
                sleep 5
              done
              ycsb_load_cmd="./bin/ycsb load foundationdb -s \
                -P $workload \
                -p foundationdb.apiversion=620 \
                -p foundationdb.clusterfile=$FDB_CLUSTER_FILE \
                -p foundationdb.batchsize=$batch_size \
                -p recordcount=$num_keys \
                -p operationcount=$keys_per_host \
                -p maxexecutiontime=$max_execution_time_seconds \
                -p fieldcount=$field_count \
                -p fieldlength=$field_length \
                -p readproportion=1.0 \
                -p updateproportion=0.0 \
                -p requestdistribution=uniform 2>&1 | tee -a $log_file"

              ycsb_run_cmd="./bin/ycsb run foundationdb -s \
                -P $workload \
                -p foundationdb.apiversion=620 \
                -p foundationdb.clusterfile=$FDB_CLUSTER_FILE \
                -p foundationdb.batchsize=$batch_size \
                -p recordcount=$num_keys \
                -p operationcount=$keys_per_host \
                -p maxexecutiontime=$max_execution_time_seconds \
                -p fieldcount=$field_count \
                -p fieldlength=$field_length \
                -p readproportion=1.0 \
                -p updateproportion=0.0 \
                -p requestdistribution=uniform 2>&1 | tee -a $log_file"
              sh -c "$ycsb_load_cmd"
              sh -c "$ycsb_run_cmd"
              while true; do
                echo "Waiting for load to finish"
                sleep 20
              done
          env:
            - name: FDB_CLUSTER_FILE
              value: /mnt/config-volume/cluster-file
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/config-volume
      volumes:
        - name: config-volume
          configMap:
            name: fdb-cluster-config
